M48
; DRILL file {KiCad (6.0.7)} date Tue Aug 30 17:51:19 2022
; FORMAT={2:4/ absolute / inch / suppress leading zeros}
; #@! TF.CreationDate,2022-08-30T17:51:19+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH,TZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0335
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X62993Y-35828
X67077Y-40848
T2
X60630Y-38309
X60630Y-40041
T0
M30
